include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    artifact-name: ergonaut-one-left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    artifact-name: ergonaut-one-right
  - board: seeeduino_xiao_ble
    shield: settings_reset
