parse_config:
  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&shift_word": $$mdi:apple-keyboard-shift$$
    "&u_bootloader": $$tabler:progress-down$$

    "&kp LA(LGUI)": "⌥⌘"
    "&kp RA(RGUI)": "⌘⌥"

    "&bt BT_CLR": $$tabler:bluetooth-x$$
    "&bt BT_SEL 0": { t: "$$tabler:bluetooth$$", h: 0 }
    "&bt BT_SEL 1": { t: "$$tabler:bluetooth$$", h: 1 }
    "&bt BT_SEL 2": { t: "$$tabler:bluetooth$$", h: 2 }
    "&bt BT_SEL 3": { t: "$$tabler:bluetooth$$", h: 3 }
    "&bt BT_SEL 4": { t: "$$tabler:bluetooth$$", h: 4 }
    "&bt BT_SEL 5": { t: "$$tabler:bluetooth$$", h: 5 }

  zmk_combos:
    space_hold: {align: bottom}
    l_cmd_opt: {align: top, hidden: true}
    r_cmd_opt: {align: top, hidden: true}

  zmk_keycode_map:
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    LC(LA(LS(LGUI))): $$mdi:rhombus$$
    BSPC: $$tabler:backspace$$
    DEL: $$tabler:square-x$$
    # ESC: $$mdi:keyboard-esc$$
    RET: $$tabler:corner-down-left$$
    SPACE: $$tabler:space$$
    TAB: $$tabler:arrow-bar-to-right$$
    F14: $$tabler:brightness-down$$
    F15: $$tabler:brightness-up$$
    K_MUTE: $$tabler:volume-3$$
    C_VOL_DN: $$tabler:volume-2$$
    C_VOL_UP: $$tabler:volume$$
    C_NEXT: $$tabler:player-skip-forward$$
    C_PREV: $$tabler:player-skip-back$$
    C_PP: $$tabler:player-play$$
    UP: $$tabler:arrow-up$$
    RIGHT: $$tabler:arrow-right$$
    DOWN: $$tabler:arrow-down$$
    LEFT: $$tabler:arrow-left$$
    "LS(LG(LBKT))": "PREV TAB"
    "LS(LG(RBKT))": "NEXT TAB"

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
draw_config:
  footer_text: 'zakj/one-zmk-config'
  dark_mode: auto
